# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solvecdp',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/solvecdp',
                'lib_path': 'solvecdp'},
  'syms': { 'solvecdp.core': { 'solvecdp.core.JsCDP': ('core.html#jscdp', 'solvecdp/core.py'),
                               'solvecdp.core.JsCDP.connect': ('core.html#jscdp.connect', 'solvecdp/core.py'),
                               'solvecdp.core.cdp_yolo': ('core.html#cdp_yolo', 'solvecdp/core.py')}}}
