"""Source and API details"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cdp_search', 'js_cdp', 'JsCDP', 'JsSub', 'JsCDPDomain', 'JsCDPMethod', 'AXNode', 'AXTree', 'build_ax_tree',
           'cdp_yolo']

# %% ../nbs/00_core.ipynb #34dc06ce
from fastcore.utils import *
import json, asyncio, inspect, base64
from contextlib import asynccontextmanager
from dialoghelper import *

# %% ../nbs/00_core.ipynb #930c2391
if '__file__' not in globals():
    _root = Path.cwd()
    if not (Path.cwd()/'pyproject.toml').exists(): _root = _root.parent
    __file__ = _root/'solvecdp'/'core.py'

_path = Path(__file__).parent
_bp = (_path/'browser_protocol.json').read_json()
_jp = (_path/'js_protocol.json').read_json()
_cdp_domains = _bp['domains'] + _jp['domains']

# %% ../nbs/00_core.ipynb #12182cb2
def cdp_search(q:str):
    "Search CDP domains and commands by name or description"
    q = q.lower()
    res = []
    for d in _cdp_domains:
        for cmd in d.get('commands', []):
            desc = cmd.get('description', '')
            if q in cmd['name'].lower() or q in desc.lower():
                res.append(f"{d['domain']}.{cmd['name']}: {desc[:120]}")
        for evt in d.get('events', []):
            desc = evt.get('description', '')
            if q in evt['name'].lower() or q in desc.lower():
                res.append(f"  evt {d['domain']}.{evt['name']}: {desc[:120]}")
    return '\n'.join(res)

# %% ../nbs/00_core.ipynb #504551f1
async def js_cdp(method, tabId=None, **params):
    res = (await event_get_a('cdp-send', tabId=tabId, method=method, params=params)).result
    return first(res.values()) if res and len(res)==1 else res

# %% ../nbs/00_core.ipynb #2bc182b9
def _lower1(s): return s[0].lower() + s[1:]
def _upper1(s): return s[0].upper() + s[1:]

# %% ../nbs/00_core.ipynb #0b40661b
class JsCDP:
    "Chrome DevTools Protocol via JS bridge with event support"
    def __init__(self, tid): self.tid,self._sub_id = tid,0

    @classmethod
    async def new(cls, tid=None, url='about:blank', active=False):
        if tid: await event_get_a('cdp-attach', tabId=tid)
        else:
            r = await event_get_a('cdp-new-tab', url=url, active=active)
            tid = r.result['tabId']
        self = cls(tid)
        await self('Page.enable')
        await self('Network.enable')
        await self('Page.setLifecycleEventsEnabled', enabled=True)
        return self

    async def __call__(self, method, **params): return await js_cdp(method, tabId=self.tid, **params)

    def __getattr__(self, domain):
        if domain.startswith('_'): raise AttributeError()
        return JsCDPDomain(self, _upper1(domain))

    async def close(self): await event_get_a('cdp-close-tab', tabId=self.tid)
    async def detach(self): await event_get_a('cdp-detach', tabId=self.tid)
    async def __aenter__(self): return self
    async def __aexit__(self, *exc): await self.detach()

    def __del__(self):
        try: asyncio.get_event_loop().create_task(self.detach())
        except Exception: pass

# %% ../nbs/00_core.ipynb #1b014de9
class JsSub:
    def __init__(self, cdp, events): self.cdp,self.events,self.seq = cdp,events,0
    async def __call__(self, timeout=10):
        self.seq += 1
        return await pop_data_a(f'{self.sub_id}:{self.seq}', timeout)
    async def __aenter__(self):
        self.cdp._sub_id += 1
        self.sub_id = f'jsc_{self.cdp.tid}_{self.cdp._sub_id}'
        await event_get_a('cdp-subscribe', tabId=self.cdp.tid, subId=self.sub_id, events=self.events)
        return self
    async def __aexit__(self, *exc): await self.cdp.unsubscribe(self.sub_id)

@patch
async def unsubscribe(self:JsCDP, sub_id): await event_get_a('cdp-unsubscribe', tabId=self.tid, subId=sub_id)

@patch
def on(self:JsCDP, *events): return JsSub(self, events)

# %% ../nbs/00_core.ipynb #0af68b93
_domains = {d['domain']: d for d in _cdp_domains}

def _find_cmd(domain, method):
    d = _domains.get(domain, {})
    return first(c for c in d.get('commands', []) if c['name'] == method)

def _cmd_sig(cmd):
    _P = inspect.Parameter
    ps = [_P(p['name'], _P.KEYWORD_ONLY, default=None if p.get('optional') else _P.empty) for p in cmd.get('parameters', [])]
    return inspect.Signature(ps)

def _cmd_doc(domain, method, cmd):
    doc = f"{domain}.{method}"
    if cmd.get('description'): doc += f" - {cmd['description']}"
    for p in cmd.get('parameters', []):
        opt = ' (optional)' if p.get('optional') else ''
        doc += f"\n  {p['name']}{opt}: {p.get('description', '')}"
    return doc

# %% ../nbs/00_core.ipynb #ac370497
class JsCDPDomain:
    def __init__(self, cdp, domain): store_attr()
    def __getattr__(self, method):
        if method.startswith('_'): raise AttributeError()
        return JsCDPMethod(self.cdp, self.domain, method)
    def __dir__(self):
        d = _domains.get(self.domain, {})
        return [c['name'] for c in d.get('commands', [])] + [e['name'] for e in d.get('events', [])]

class JsCDPMethod:
    def __init__(self, cdp, domain, method):
        store_attr()
        if (cmd := _find_cmd(domain, method)):
            self.__doc__ = _cmd_doc(domain, method, cmd)
            self.__signature__ = _cmd_sig(cmd)
    async def __call__(self, **kw): return await self.cdp(f'{self.domain}.{self.method}', **kw)

# %% ../nbs/00_core.ipynb #39b7647d
@patch
async def wait_for(self:JsCDP, expr, timeout=10):
    "Wait for JS expression to be truthy, return its value"
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        r = await self.eval(expr)
        if r: return r
        await asyncio.sleep(0.05)
    raise TimeoutError(f'Timed out waiting for: {expr}')

@patch
async def wait_for_selector(self:JsCDP, sel, timeout=10):
    "Wait for CSS selector to match an element"
    return await self.wait_for(f'!!document.querySelector("{sel}")', timeout)

@patch
async def eval(self:JsCDP, expr):
    res = await self.runtime.evaluate(expression=expr)
    return res.get("value") if res else res

# %% ../nbs/00_core.ipynb #9814014d
@patch
async def wait_for_ready(self:JsCDP, timeout=10, idle_ms=500):
    "Wait until network is idle for idle_ms"
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        async with self.on('Network.requestWillBeSent') as q:
            r = await q(idle_ms/1000)
            if not r or r.get('js_status')=='timeout': return
    raise TimeoutError('Timed out waiting for network idle')

@patch
async def goto(self:JsCDP, url, **kwargs):
    "Navigate to url and wait for load+idle"
    await self.page.navigate(url=url)
    await self.wait_for_ready(**kwargs)

# %% ../nbs/00_core.ipynb #11ceac02
@patch(as_prop=True)
async def pages(self:JsCDP):
    targets = (await event_get_a('cdp-get-targets')).result
    return [t for t in targets if t.get('type') == 'page']

# %% ../nbs/00_core.ipynb #b71ec061
@patch
async def screenshot(self:JsCDP):
    from IPython.display import Image
    b64 = await self.page.captureScreenshot(format='png')
    return Image(base64.b64decode(b64))

# %% ../nbs/00_core.ipynb #258e3058
class AXNode:
    "Chrome accessibility tree node with compact repr"
    def __init__(self, raw):
        self.role = nested_idx(raw, 'role', 'value') or ''
        self.name = nested_idx(raw, 'name', 'value') or ''
        self.props = {p['name']: nested_idx(p, 'value', 'value') for p in raw.get('properties', [])}
        self.children = []
        self.node_id = raw.get('nodeId')
        self.backend_id = raw.get('backendDOMNodeId')
        self.ignored = raw.get('ignored', False)
        self._raw = raw

    def _repr_markdown_(self, depth=0):
        pre = '  ' * depth
        ps = ''.join(f' `{k}={v}`' for k,v in self.props.items() if v not in (False, None, '', 'false'))
        bid = f' [#{self.backend_id}]' if self.backend_id else ''
        line = f'{pre}- **{self.role}** "{self.name}"{ps}{bid}'
        return '\n'.join([line] + [c._repr_markdown_(depth+1) for c in self.children])

    __str__ = __repr__ = _repr_markdown_

class AXTree(AXNode):
    def _repr_markdown_(self): return f'<div class="prose">\n\n{super()._repr_markdown_(0)}\n\n</div>'

# %% ../nbs/00_core.ipynb #492259b0
def _simplify(node):
    node.children = [n for c in node.children for n in _simplify(c)]
    if node.role in ('none', 'generic', 'paragraph') and not node.name:
        if not node.children: return []
        return node.children  # splice children up
    return [node]

def build_ax_tree(nodes):
    "Build AXNode tree from flat CDP accessibility node list"
    by_id = {}
    for raw in nodes:
        n = AXNode(raw)
        by_id[n.node_id] = n
    for raw in nodes:
        parent = by_id.get(raw.get('nodeId'))
        for cid in raw.get('childIds', []):
            if (child := by_id.get(cid)): parent.children.append(child)
    if not nodes: return
    root = by_id.get(nodes[0]['nodeId'])
    if not (result := _simplify(root)): return None
    result = result[0]
    result.__class__ = AXTree
    return result

# %% ../nbs/00_core.ipynb #d3e7a635
@patch
async def ax_tree(self:JsCDP, sid=None):
    "Get accessibility tree for session"
    await self.accessibility.enable(sid=sid)
    return build_ax_tree(await self.accessibility.getFullAXTree(sid=sid))

# %% ../nbs/00_core.ipynb #d317c80b
@patch
def find(self:AXNode, role=None, name=None):
    "Find first descendant matching role and/or name substring"
    if (not role or role == self.role) and (not name or name in self.name): return self
    for c in self.children:
        if (r := c.find(role, name)): return r

@patch
def find_id(self:AXNode, role=None, name=None):
    "Find first descendant matching role and/or name substring"
    res = self.find(role, name)
    return res.backend_id if res else None

@patch
def find_all(self:AXNode, role=None, name=None):
    "Find all descendants matching role and/or name substring"
    res = []
    if (not role or role == self.role) and (not name or name in self.name): res.append(self)
    for c in self.children: res += c.find_all(role, name)
    return res

# %% ../nbs/00_core.ipynb #28b872d9
@patch
async def js_node(self:JsCDP, fn, backendNodeId, sid=None):
    obj = await self.DOM.resolveNode(sid=sid, backendNodeId=backendNodeId)
    return await self.runtime.callFunctionOn(sid=sid, functionDeclaration=fn,
                                              objectId=obj['objectId'])

@patch
async def js_node_run(self:JsCDP, code, backendNodeId, sid=None):
    return await self.js_node(f'function() {{ {code} }}', backendNodeId, sid=sid)

@patch
async def click(self:JsCDP, backendNodeId, sid=None):
    await self.js_node_run('this.click()', backendNodeId, sid=sid)

# %% ../nbs/00_core.ipynb #3e826905
@patch
async def fill_text(self:JsCDP, backendNodeId, text, sid=None):
    await self.DOM.focus(sid=sid, backendNodeId=backendNodeId)
    await self.input.insertText(sid=sid, text=text)

# %% ../nbs/00_core.ipynb #3eec012b
@patch
async def click_and_wait(self:JsCDP, backendNodeId, **kwargs):
    "Click element and wait for load+idle"
    await self.js_node_run('this.click()', backendNodeId)
    await self.wait_for_ready(**kwargs)

# %% ../nbs/00_core.ipynb #605c1669
def cdp_yolo():
    "Allow all CDP classes in safepyrun"
    from safepyrun import allow
    allow({JsCDP:..., JsCDPDomain:..., JsCDPMethod:...})
    allow({AXNode:..., AXTree:...})
