"""Drive the user's Chrome from a solveit kernel

Docs: https://AnswerDotAI.github.io/solvecdp/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['JsCDP', 'cdp_yolo']

# %% ../nbs/00_core.ipynb #34dc06ce
from fastcore.utils import *
from dialoghelper import *
from fastcdp.ext import *
import fastcdp.ext

# %% ../nbs/00_core.ipynb #633a6930
class JsCDP(ExtCDP):
    "CDP over the solveit-chrome extension: frames relayed via solveit's `/wsx` channel"
    @classmethod
    async def connect(cls,
        chan='cdp', # Relay channel name the extension serves
        debug=None # Print events as they arrive?
    ):
        return await super().connect(await Channel.connect(chan), debug=debug)

# %% ../nbs/00_core.ipynb #8fbd7193
def cdp_yolo():
    "Allow all CDP classes in safepyrun"
    from pyskills import allow
    fastcdp.ext.cdp_yolo()
    allow({JsCDP:...})
